language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install -r requirements/test.txt
  - python setup.py install
script:
  - pytest --cov=flask_authentic --cov-config .coveragerc --flake8
after_success:
  - pip install codecov
  - codecov
