language: python
python:
  - '3.6'
install:
  - pip install -r requirements/test.txt
  - python setup.py install
script:
  - pytest --cov=flask_authentic --cov-config .coveragerc tests
after_success:
  - pip install codecov
  - codecov
